name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with retry
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: ./run-tests.sh

      - name: Check for common errors
        run: |
          if grep -i "timeout" test-output.log; then
            echo "⚠️ Timeout Error detected – retrying..."
            exit 1
          elif grep -i "connection refused" test-output.log; then
            echo "⚠️ Network Error detected – retrying..."
            exit 1
          else
            echo "✅ No known errors detected."
          fi

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: ./deploy.sh

  rollback:
    needs: deploy
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rollback Deployment
        run: ./rollback.sh

