name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Make scripts executable
        run: chmod +x run-tests.sh

      - name: Run tests with self-healing retries
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 10
          command: ./run-tests.sh

      - name: Final log check (after retries)
        run: |
          echo "🔍 Final log analysis..."
          python3 analyze_logs.py || true

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: ./deploy.sh

  rollback:
    needs: deploy
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rollback Deployment
        run: ./rollback.sh

