name: Self-Healing CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Make scripts executable
        run: chmod +x run-tests.sh analyzer_log.sh

      - name: Run self-healing tests
        run: ./run-tests.sh

